# Generated by Django 3.2.5 on 2021-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('correoElectronico', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Correo Electronico')),
                ('nombreApellido', models.CharField(max_length=40, verbose_name='Nombre y Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion')),
                ('contrasenna', models.CharField(max_length=10, verbose_name='Contrasenna')),
            ],
        ),
    ]
