# Generated by Django 3.2.5 on 2021-07-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contacto_numerocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrarTrabajo',
            fields=[
                ('nombreTrabajo', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre Trabajo')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('costoTrabajo', models.IntegerField(verbose_name='Costo del trabajo')),
                ('fechaTrabajo', models.DateField(verbose_name='Fecha trabajo')),
            ],
        ),
    ]
